name: C++ CI

on:
  pull_request

jobs:
  test:
    name: Tests in ${{ matrix.build_type }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [Release, Debug, RelWithDebInfo]

    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install binutils g++-10 cmake valgrind

    - name: Build main
      run: CXX=g++-10 ./build.sh ${{ matrix.build_type }}

    - name: Test main
      run: CXX=g++-10 ./test.sh ${{ matrix.build_type }}

    - if: ${{ matrix.build_type == 'RelWithDebInfo' }}
      name: Test main with valgrind
      run: CXX=g++-10 ./test-valgrind.sh
